apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: develop
type: Opaque
stringData:
  mysql-root-password: rootpass
  mysql-user: wp_user
  mysql-password: wp_pass
  mysql-database: wordpress_db
  wordpress-db-host: sql.develop.svc.cluster.local
