apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql
  namespace: develop
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo 
  serviceName: mysql  
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: sqlstorage
          mountPath: /var/lib/mysql
      volumes:
      - name: sqlstorage
        persistentVolumeClaim:
          claimName: sqlpvc
