apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlpvc
  namespace: develop
spec:
  volumeName: sqlpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
