apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webpvc
  namespace: develop
spec:
  volumeName: webpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
