apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.encodedRootPassword }}
  mysql-user: {{ .Values.mysql.encodedUser }}
  mysql-password: {{ .Values.mysql.encodedPassword }}
  mysql-database: {{ .Values.mysql.encodedDatabase }}
  wordpress-db-host: {{ .Values.secret.encodedDBHost }}
