apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: web
spec:
  selector:
    app: web
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.web.name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}

