apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.web.name }}pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.web.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: {{ .Values.web.hostPath }}
